name       : python-enum34
version    : 1.1.10
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/e/enum34/enum34-1.1.10.tar.gz : cce6a7477ed816bd2542d03d53db9f0db935dd013b70f336a95c73979289f248
homepage   : https://pypi.org/project/enum34/
license    : BSD-3-Clause
component  : programming.python
summary    : Python 3.4 Enum backport
description: |
    An enumeration is a set of symbolic names (members) bound to unique, constant values. Within an enumeration, the members can be compared by identity, and the enumeration itself can be iterated over.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
