name       : python-enum34
version    : 1.1.2
release    : 1
source     :
    - https://pypi.python.org/packages/source/e/enum34/enum34-1.1.2.tar.gz : 2475d7fcddf5951e92ff546972758802de5260bf409319a9f1934e6bbc8b1dc7
license    : BSD-Clause
summary    : Python 3.4 Enum backport
description: |
    Python 3.4 Enum backport
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
