name       : python-enum34
version    : 1.1.6
release    : 2
source     :
    - https://pypi.python.org/packages/bf/3e/31d502c25302814a7c2f1d3959d2a3b3f78e509002ba91aea64993936876/enum34-1.1.6.tar.gz : 8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1
license    : BSD-Clause
component  : programming.python
summary    : Python 3.4 Enum backport
description: |
    Python 3.4 Enum backport
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
